name = "gamification-app"
main = "workers/src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "gamification-app-prod"

[[d1_databases]]
binding = "DB"
database_name = "gamification-db"
database_id = "3b2d2589-1661-42dc-ae39-eaf6ddacacdc"

[[kv_namespaces]]
binding = "SESSIONS"
id = "0a93b4381423409281c00ebe5a294762"
preview_id = "7c3659065e7f43ac952ff7f31a4331e9"

[vars]
ENVIRONMENT = "production"

